#create docker compose file for the application nestjs and postgresql
version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=SCVApp
    ports:
      - 80:5050
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SCVApp
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
